'''
 Nd Genie Ops Object Outputs for IOSXR.
'''

class NdOutput(object):
    
    ShowIpv6Neighbors = {
        'interfaces': {
            'GigabitEthernet0/0/0/0.90': {
                'interface': 'Gi0/0/0/0.90',
                'neighbors': {
                    'fe80::f816:3eff:fe26:1224': {
                        'age': '131',
                        'ip': 'fe80::f816:3eff:fe26:1224',
                        'link_layer_address': 'fa16.3e26.1224',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.90': {
                'interface': 'Gi0/0/0/1.90',
                'neighbors': {
                    'fe80::5c00:40ff:fe02:7': {
                        'age': '144',
                        'ip': 'fe80::5c00:40ff:fe02:7',
                        'link_layer_address': '5e00.4002.0007',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.110': {
                'interface': 'Gi0/0/0/0.110',
                'neighbors': {
                    'fe80::f816:3eff:fe26:1224': {
                        'age': '99',
                        'ip': 'fe80::f816:3eff:fe26:1224',
                        'link_layer_address': 'fa16.3e26.1224',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.115': {
                'interface': 'Gi0/0/0/0.115',
                'neighbors': {
                    'fe80::f816:3eff:fe26:1224': {
                        'age': '46',
                        'ip': 'fe80::f816:3eff:fe26:1224',
                        'link_layer_address': 'fa16.3e26.1224',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.120': {
                'interface': 'Gi0/0/0/0.120',
                'neighbors': {
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.390': {
                'interface': 'Gi0/0/0/0.390',
                'neighbors': {
                    'fe80::f816:3eff:fe26:1224': {
                        'age': '137',
                        'ip': 'fe80::f816:3eff:fe26:1224',
                        'link_layer_address': 'fa16.3e26.1224',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.410': {
                'interface': 'Gi0/0/0/0.410',
                'neighbors': {
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.415': {
                'interface': 'Gi0/0/0/0.415',
                'neighbors': {
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.420': {
                'interface': 'Gi0/0/0/0.420',
                'neighbors': {
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.110': {
                'interface': 'Gi0/0/0/1.110',
                'neighbors': {
                    'fe80::5c00:40ff:fe02:7': {
                        'age': '167',
                        'ip': 'fe80::5c00:40ff:fe02:7',
                        'link_layer_address': '5e00.4002.0007',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.115': {
                'interface': 'Gi0/0/0/1.115',
                'neighbors': {
                    'fe80::5c00:40ff:fe02:7': {
                        'age': '137',
                        'ip': 'fe80::5c00:40ff:fe02:7',
                        'link_layer_address': '5e00.4002.0007',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.120': {
                'interface': 'Gi0/0/0/1.120',
                'neighbors': {
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.390': {
                'interface': 'Gi0/0/0/1.390',
                'neighbors': {
                    'fe80::5c00:40ff:fe02:7': {
                        'age': '101',
                        'ip': 'fe80::5c00:40ff:fe02:7',
                        'link_layer_address': '5e00.4002.0007',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.410': {
                'interface': 'Gi0/0/0/1.410',
                'neighbors': {
                    'fe80::5c00:40ff:fe02:7': {
                        'age': '121',
                        'ip': 'fe80::5c00:40ff:fe02:7',
                        'link_layer_address': '5e00.4002.0007',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.415': {
                'interface': 'Gi0/0/0/1.415',
                'neighbors': {
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.420': {
                'interface': 'Gi0/0/0/1.420',
                'neighbors': {
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                    },
                },
            },
        },
    }

    ShowIpv6NeighborsDetail = {
        'interfaces': {
            'GigabitEthernet0/0/0/0.90': {
                'interface': 'Gi0/0/0/0.90',
                'neighbors': {
                    'fe80::f816:3eff:fe26:1224': {
                        'age': '138',
                        'ip': 'fe80::f816:3eff:fe26:1224',
                        'link_layer_address': 'fa16.3e26.1224',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': 'Y',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'dynamic',
                    },
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': '-',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.90': {
                'interface': 'Gi0/0/0/1.90',
                'neighbors': {
                    'fe80::5c00:40ff:fe02:7': {
                        'age': '151',
                        'ip': 'fe80::5c00:40ff:fe02:7',
                        'link_layer_address': '5e00.4002.0007',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': 'Y',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'dynamic',
                    },
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': '-',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.110': {
                'interface': 'Gi0/0/0/0.110',
                'neighbors': {
                    'fe80::f816:3eff:fe26:1224': {
                        'age': '114',
                        'ip': 'fe80::f816:3eff:fe26:1224',
                        'link_layer_address': 'fa16.3e26.1224',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': 'Y',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'dynamic',
                    },
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': '-',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.115': {
                'interface': 'Gi0/0/0/0.115',
                'neighbors': {
                    'fe80::f816:3eff:fe26:1224': {
                        'age': '69',
                        'ip': 'fe80::f816:3eff:fe26:1224',
                        'link_layer_address': 'fa16.3e26.1224',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': 'Y',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'dynamic',
                    },
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': '-',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.120': {
                'interface': 'Gi0/0/0/0.120',
                'neighbors': {
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': '-',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.390': {
                'interface': 'Gi0/0/0/0.390',
                'neighbors': {
                    'fe80::f816:3eff:fe26:1224': {
                        'age': '151',
                        'ip': 'fe80::f816:3eff:fe26:1224',
                        'link_layer_address': 'fa16.3e26.1224',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': 'Y',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'dynamic',
                    },
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': '-',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.410': {
                'interface': 'Gi0/0/0/0.410',
                'neighbors': {
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': '-',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.415': {
                'interface': 'Gi0/0/0/0.415',
                'neighbors': {
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': '-',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.420': {
                'interface': 'Gi0/0/0/0.420',
                'neighbors': {
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': '-',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.110': {
                'interface': 'Gi0/0/0/1.110',
                'neighbors': {
                    'fe80::5c00:40ff:fe02:7': {
                        'age': '17',
                        'ip': 'fe80::5c00:40ff:fe02:7',
                        'link_layer_address': '5e00.4002.0007',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': 'Y',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'dynamic',
                    },
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': '-',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.115': {
                'interface': 'Gi0/0/0/1.115',
                'neighbors': {
                    'fe80::5c00:40ff:fe02:7': {
                        'age': '165',
                        'ip': 'fe80::5c00:40ff:fe02:7',
                        'link_layer_address': '5e00.4002.0007',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': 'Y',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'dynamic',
                    },
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': '-',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.120': {
                'interface': 'Gi0/0/0/1.120',
                'neighbors': {
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': '-',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.390': {
                'interface': 'Gi0/0/0/1.390',
                'neighbors': {
                    'fe80::5c00:40ff:fe02:7': {
                        'age': '100',
                        'ip': 'fe80::5c00:40ff:fe02:7',
                        'link_layer_address': '5e00.4002.0007',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': 'Y',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'dynamic',
                    },
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': '-',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.410': {
                'interface': 'Gi0/0/0/1.410',
                'neighbors': {
                    'fe80::5c00:40ff:fe02:7': {
                        'age': '125',
                        'ip': 'fe80::5c00:40ff:fe02:7',
                        'link_layer_address': '5e00.4002.0007',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': 'Y',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'dynamic',
                    },
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': '-',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.415': {
                'interface': 'Gi0/0/0/1.415',
                'neighbors': {
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': '-',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.420': {
                'interface': 'Gi0/0/0/1.420',
                'neighbors': {
                    'Mcast adjacency': {
                        'age': '-',
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'location': '0/0/CPU0',
                        'static': '-',
                        'dynamic': '-',
                        'sync': '-',
                        'serg_flags': 'ff',
                        'origin': 'other',
                    },
                },
            },
        },
    }
    
    ShowIpv6VrfAllInterface = {
        'Bundle-Ether12': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'default',
            'vrf_id': '0x60000000',
            'enabled': False,
        },
        'Bundle-Ether23': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'default',
            'vrf_id': '0x60000000',
            'enabled': False,
        },
        'Loopback0': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'default',
            'vrf_id': '0x60000000',
            'enabled': True,
            'ipv6': {
                '2001:2:2:2::2/128': {
                    'ipv6': '2001:2:2:2::2',
                    'ipv6_prefix_length': '128',
                    'ipv6_subnet': '2001:2:2:2::2',
                },
                'ipv6_link_local': 'fe80::8152:bfff:fed0:fbb5',
                'ipv6_groups': ['ff02::1:ff00:2', 'ff02::1:ffd0:fbb5', 'ff02::2', 'ff02::1', 'ff02::16', 'ff02::d'],
                'ipv6_mtu': '1500',
                'ipv6_mtu_available': '1500',
                'icmp_redirects': 'disabled',
                'nd_dad': 'disabled',
                'dad_attempts': '0',
                'nd_reachable_time': '0',
                'nd_cache_limit': '0',
                'nd_adv_retrans_int': '0',
                'stateless_autoconfig': True,
                'table_id': '0xe0800000',
                'complete_protocol_adj': '0',
                'complete_glean_adj': '0',
                'incomplete_protocol_adj': '0',
                'incomplete_glean_adj': '0',
                'dropped_protocol_req': '0',
                'dropped_glean_req': '0',
            },
        },
        'Loopback300': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'VRF1',
            'vrf_id': '0x60000001',
            'enabled': True,
            'ipv6': {
                '2001:2:2:2::2/128': {
                    'ipv6': '2001:2:2:2::2',
                    'ipv6_prefix_length': '128',
                    'ipv6_subnet': '2001:2:2:2::2',
                },
                'ipv6_link_local': 'fe80::8152:bfff:fed0:fbb5',
                'ipv6_groups': ['ff02::1:ff00:2', 'ff02::1:ffd0:fbb5', 'ff02::2', 'ff02::1', 'ff02::16', 'ff02::d'],
                'ipv6_mtu': '1500',
                'ipv6_mtu_available': '1500',
                'icmp_redirects': 'disabled',
                'nd_dad': 'disabled',
                'dad_attempts': '0',
                'nd_reachable_time': '0',
                'nd_cache_limit': '0',
                'nd_adv_retrans_int': '0',
                'stateless_autoconfig': True,
                'table_id': '0xe0800001',
                'complete_protocol_adj': '0',
                'complete_glean_adj': '0',
                'incomplete_protocol_adj': '0',
                'incomplete_glean_adj': '0',
                'dropped_protocol_req': '0',
                'dropped_glean_req': '0',
            },
        },
        'MgmtEth0/RP0/CPU0/0': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'management',
            'vrf_id': '0x60000002',
            'enabled': False,
        },
        'GigabitEthernet0/0/0/0': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'default',
            'vrf_id': '0x60000000',
            'enabled': False,
        },
        'GigabitEthernet0/0/0/0.90': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'default',
            'vrf_id': '0x60000000',
            'enabled': True,
            'ipv6': {
                '2001:10:12:90::2/64': {
                    'ipv6': '2001:10:12:90::2',
                    'ipv6_prefix_length': '64',
                    'ipv6_subnet': '2001:10:12:90::',
                },
                'ipv6_link_local': 'fe80::f816:3eff:fe0f:b2ec',
                'ipv6_groups': ['ff02::1:ff00:2', 'ff02::1:ff0f:b2ec', 'ff02::2', 'ff02::1', 'ff02::a'],
                'ipv6_mtu': '1518',
                'ipv6_mtu_available': '1500',
                'icmp_redirects': 'disabled',
                'icmp_unreachables': 'enabled',
                'nd_dad': 'enabled',
                'dad_attempts': '1',
                'nd_reachable_time': '0',
                'nd_cache_limit': '1000000000',
                'nd_adv_retrans_int': '0',
                'stateless_autoconfig': True,
                'table_id': '0xe0800000',
                'complete_protocol_adj': '0',
                'complete_glean_adj': '1',
                'incomplete_protocol_adj': '0',
                'incomplete_glean_adj': '0',
                'dropped_protocol_req': '0',
                'dropped_glean_req': '0',
                'nd_suppress': True,
            },
        },
        'GigabitEthernet0/0/0/0.110': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'default',
            'vrf_id': '0x60000000',
            'enabled': True,
            'ipv6': {
                '2001:10:12:110::2/64': {
                    'ipv6': '2001:10:12:110::2',
                    'ipv6_prefix_length': '64',
                    'ipv6_subnet': '2001:10:12:110::',
                },
                'ipv6_link_local': 'fe80::f816:3eff:fe0f:b2ec',
                'ipv6_groups': ['ff02::1:ff00:2', 'ff02::1:ff0f:b2ec', 'ff02::2', 'ff02::1', 'ff02::16', 'ff02::5', 'ff02::6', 'ff02::d'],
                'ipv6_mtu': '1518',
                'ipv6_mtu_available': '1500',
                'icmp_redirects': 'disabled',
                'icmp_unreachables': 'enabled',
                'nd_dad': 'enabled',
                'dad_attempts': '1',
                'nd_reachable_time': '0',
                'nd_cache_limit': '1000000000',
                'nd_adv_retrans_int': '0',
                'nd_adv_duration': '160-240',
                'nd_router_adv': '1800',
                'stateless_autoconfig': True,
                'table_id': '0xe0800000',
                'complete_protocol_adj': '1',
                'complete_glean_adj': '0',
                'incomplete_protocol_adj': '0',
                'incomplete_glean_adj': '0',
                'dropped_protocol_req': '0',
                'dropped_glean_req': '0',
            },
        },
        'GigabitEthernet0/0/0/0.115': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'default',
            'vrf_id': '0x60000000',
            'enabled': True,
            'ipv6': {
                '2001:10:12:115::2/64': {
                    'ipv6': '2001:10:12:115::2',
                    'ipv6_prefix_length': '64',
                    'ipv6_subnet': '2001:10:12:115::',
                },
                'ipv6_link_local': 'fe80::f816:3eff:fe0f:b2ec',
                'ipv6_groups': ['ff02::1:ff00:2', 'ff02::1:ff0f:b2ec', 'ff02::2', 'ff02::1', 'ff1e:abcd:def1:2222::1', 'ff1e:abcd:def1:2222::2'],
                'ipv6_mtu': '1518',
                'ipv6_mtu_available': '1500',
                'icmp_redirects': 'disabled',
                'icmp_unreachables': 'enabled',
                'nd_dad': 'enabled',
                'dad_attempts': '1',
                'nd_reachable_time': '0',
                'nd_cache_limit': '1000000000',
                'nd_adv_retrans_int': '0',
                'nd_adv_duration': '160-240',
                'nd_router_adv': '1800',
                'stateless_autoconfig': True,
                'table_id': '0xe0800000',
                'complete_protocol_adj': '1',
                'complete_glean_adj': '0',
                'incomplete_protocol_adj': '0',
                'incomplete_glean_adj': '0',
                'dropped_protocol_req': '0',
                'dropped_glean_req': '0',
            },
        },
        'GigabitEthernet0/0/0/0.120': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'default',
            'vrf_id': '0x60000000',
            'enabled': True,
            'ipv6': {
                '2001:10:12:120::2/64': {
                    'ipv6': '2001:10:12:120::2',
                    'ipv6_prefix_length': '64',
                    'ipv6_subnet': '2001:10:12:120::',
                },
                'ipv6_link_local': 'fe80::f816:3eff:fe0f:b2ec',
                'ipv6_groups': ['ff02::1:ff00:2', 'ff02::1:ff0f:b2ec', 'ff02::2', 'ff02::1'],
                'ipv6_mtu': '1518',
                'ipv6_mtu_available': '1500',
                'icmp_redirects': 'disabled',
                'icmp_unreachables': 'enabled',
                'nd_dad': 'enabled',
                'dad_attempts': '1',
                'nd_reachable_time': '0',
                'nd_cache_limit': '1000000000',
                'nd_adv_retrans_int': '0',
                'nd_adv_duration': '160-240',
                'nd_router_adv': '1800',
                'stateless_autoconfig': True,
                'table_id': '0xe0800000',
                'complete_protocol_adj': '0',
                'complete_glean_adj': '0',
                'incomplete_protocol_adj': '0',
                'incomplete_glean_adj': '0',
                'dropped_protocol_req': '0',
                'dropped_glean_req': '0',
            },
        },
        'GigabitEthernet0/0/0/0.390': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'VRF1',
            'vrf_id': '0x60000001',
            'enabled': True,
            'ipv6': {
                '2001:10:12:90::2/64': {
                    'ipv6': '2001:10:12:90::2',
                    'ipv6_prefix_length': '64',
                    'ipv6_subnet': '2001:10:12:90::',
                },
                'ipv6_link_local': 'fe80::f816:3eff:fe0f:b2ec',
                'ipv6_groups': ['ff02::1:ff00:2', 'ff02::1:ff0f:b2ec', 'ff02::2', 'ff02::1', 'ff02::a'],
                'ipv6_mtu': '1518',
                'ipv6_mtu_available': '1500',
                'icmp_redirects': 'disabled',
                'icmp_unreachables': 'enabled',
                'nd_dad': 'enabled',
                'dad_attempts': '1',
                'nd_reachable_time': '0',
                'nd_cache_limit': '1000000000',
                'nd_adv_retrans_int': '0',
                'nd_adv_duration': '160-240',
                'nd_router_adv': '1800',
                'stateless_autoconfig': True,
                'table_id': '0xe0800001',
                'complete_protocol_adj': '1',
                'complete_glean_adj': '0',
                'incomplete_protocol_adj': '0',
                'incomplete_glean_adj': '0',
                'dropped_protocol_req': '0',
                'dropped_glean_req': '0',
            },
        },
        'GigabitEthernet0/0/0/0.410': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'VRF1',
            'vrf_id': '0x60000001',
            'enabled': True,
            'ipv6': {
                '2001:10:12:110::2/64': {
                    'ipv6': '2001:10:12:110::2',
                    'ipv6_prefix_length': '64',
                    'ipv6_subnet': '2001:10:12:110::',
                },
                'ipv6_link_local': 'fe80::f816:3eff:fe0f:b2ec',
                'ipv6_groups': ['ff02::1:ff00:2', 'ff02::1:ff0f:b2ec', 'ff02::2', 'ff02::1', 'ff02::16', 'ff02::5', 'ff02::6', 'ff02::d'],
                'ipv6_mtu': '1518',
                'ipv6_mtu_available': '1500',
                'icmp_redirects': 'disabled',
                'icmp_unreachables': 'enabled',
                'nd_dad': 'enabled',
                'dad_attempts': '1',
                'nd_reachable_time': '0',
                'nd_cache_limit': '1000000000',
                'nd_adv_retrans_int': '0',
                'nd_adv_duration': '160-240',
                'nd_router_adv': '1800',
                'stateless_autoconfig': True,
                'table_id': '0xe0800001',
                'complete_protocol_adj': '0',
                'complete_glean_adj': '0',
                'incomplete_protocol_adj': '0',
                'incomplete_glean_adj': '0',
                'dropped_protocol_req': '0',
                'dropped_glean_req': '0',
            },
        },
        'GigabitEthernet0/0/0/0.415': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'VRF1',
            'vrf_id': '0x60000001',
            'enabled': True,
            'ipv6': {
                '2001:10:12:115::2/64': {
                    'ipv6': '2001:10:12:115::2',
                    'ipv6_prefix_length': '64',
                    'ipv6_subnet': '2001:10:12:115::',
                },
                'ipv6_link_local': 'fe80::f816:3eff:fe0f:b2ec',
                'ipv6_groups': ['ff02::1:ff00:2', 'ff02::1:ff0f:b2ec', 'ff02::2', 'ff02::1', 'ff1e:abcd:def1:2222::1', 'ff1e:abcd:def1:2222::2'],
                'ipv6_mtu': '1518',
                'ipv6_mtu_available': '1500',
                'icmp_redirects': 'disabled',
                'icmp_unreachables': 'enabled',
                'nd_dad': 'enabled',
                'dad_attempts': '1',
                'nd_reachable_time': '0',
                'nd_cache_limit': '1000000000',
                'nd_adv_retrans_int': '0',
                'nd_adv_duration': '160-240',
                'nd_router_adv': '1800',
                'stateless_autoconfig': True,
                'table_id': '0xe0800001',
                'complete_protocol_adj': '0',
                'complete_glean_adj': '0',
                'incomplete_protocol_adj': '0',
                'incomplete_glean_adj': '0',
                'dropped_protocol_req': '0',
                'dropped_glean_req': '0',
            },
        },
        'GigabitEthernet0/0/0/0.420': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'VRF1',
            'vrf_id': '0x60000001',
            'enabled': True,
            'ipv6': {
                '2001:10:12:120::2/64': {
                    'ipv6': '2001:10:12:120::2',
                    'ipv6_prefix_length': '64',
                    'ipv6_subnet': '2001:10:12:120::',
                },
                'ipv6_link_local': 'fe80::f816:3eff:fe0f:b2ec',
                'ipv6_groups': ['ff02::1:ff00:2', 'ff02::1:ff0f:b2ec', 'ff02::2', 'ff02::1'],
                'ipv6_mtu': '1518',
                'ipv6_mtu_available': '1500',
                'icmp_redirects': 'disabled',
                'icmp_unreachables': 'enabled',
                'nd_dad': 'enabled',
                'dad_attempts': '1',
                'nd_reachable_time': '0',
                'nd_cache_limit': '1000000000',
                'nd_adv_retrans_int': '0',
                'nd_adv_duration': '160-240',
                'nd_router_adv': '1800',
                'stateless_autoconfig': True,
                'table_id': '0xe0800001',
                'complete_protocol_adj': '0',
                'complete_glean_adj': '0',
                'incomplete_protocol_adj': '0',
                'incomplete_glean_adj': '0',
                'dropped_protocol_req': '0',
                'dropped_glean_req': '0',
            },
        },
        'GigabitEthernet0/0/0/1': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'default',
            'vrf_id': '0x60000000',
            'enabled': False,
        },
        'GigabitEthernet0/0/0/1.90': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'default',
            'vrf_id': '0x60000000',
            'enabled': True,
            'ipv6': {
                '2001:10:23:90::2/64': {
                    'ipv6': '2001:10:23:90::2',
                    'ipv6_prefix_length': '64',
                    'ipv6_subnet': '2001:10:23:90::',
                },
                'ipv6_link_local': 'fe80::f816:3eff:fe59:8f2e',
                'ipv6_groups': ['ff02::1:ff00:2', 'ff02::1:ff59:8f2e', 'ff02::2', 'ff02::1', 'ff02::a'],
                'ipv6_mtu': '1518',
                'ipv6_mtu_available': '1500',
                'icmp_redirects': 'disabled',
                'icmp_unreachables': 'enabled',
                'nd_dad': 'enabled',
                'dad_attempts': '1',
                'nd_reachable_time': '0',
                'nd_cache_limit': '1000000000',
                'nd_adv_retrans_int': '0',
                'nd_adv_duration': '160-240',
                'nd_router_adv': '1800',
                'stateless_autoconfig': True,
                'table_id': '0xe0800000',
                'complete_protocol_adj': '1',
                'complete_glean_adj': '0',
                'incomplete_protocol_adj': '0',
                'incomplete_glean_adj': '0',
                'dropped_protocol_req': '0',
                'dropped_glean_req': '0',
            },
        },
        'GigabitEthernet0/0/0/1.110': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'default',
            'vrf_id': '0x60000000',
            'enabled': True,
            'ipv6': {
                '2001:10:23:110::2/64': {
                    'ipv6': '2001:10:23:110::2',
                    'ipv6_prefix_length': '64',
                    'ipv6_subnet': '2001:10:23:110::',
                },
                'ipv6_link_local': 'fe80::f816:3eff:fe59:8f2e',
                'ipv6_groups': ['ff02::1:ff00:2', 'ff02::1:ff59:8f2e', 'ff02::2', 'ff02::1', 'ff02::16', 'ff02::5', 'ff02::6', 'ff02::d'],
                'ipv6_mtu': '1518',
                'ipv6_mtu_available': '1500',
                'icmp_redirects': 'disabled',
                'icmp_unreachables': 'enabled',
                'nd_dad': 'enabled',
                'dad_attempts': '1',
                'nd_reachable_time': '0',
                'nd_cache_limit': '1000000000',
                'nd_adv_retrans_int': '0',
                'nd_adv_duration': '160-240',
                'nd_router_adv': '1800',
                'stateless_autoconfig': True,
                'table_id': '0xe0800000',
                'complete_protocol_adj': '1',
                'complete_glean_adj': '0',
                'incomplete_protocol_adj': '0',
                'incomplete_glean_adj': '0',
                'dropped_protocol_req': '0',
                'dropped_glean_req': '0',
            },
        },
        'GigabitEthernet0/0/0/1.115': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'default',
            'vrf_id': '0x60000000',
            'enabled': True,
            'ipv6': {
                '2001:10:23:115::2/64': {
                    'ipv6': '2001:10:23:115::2',
                    'ipv6_prefix_length': '64',
                    'ipv6_subnet': '2001:10:23:115::',
                },
                'ipv6_link_local': 'fe80::f816:3eff:fe59:8f2e',
                'ipv6_groups': ['ff02::1:ff00:2', 'ff02::1:ff59:8f2e', 'ff02::2', 'ff02::1'],
                'ipv6_mtu': '1518',
                'ipv6_mtu_available': '1500',
                'icmp_redirects': 'disabled',
                'icmp_unreachables': 'enabled',
                'nd_dad': 'enabled',
                'dad_attempts': '1',
                'nd_reachable_time': '0',
                'nd_cache_limit': '1000000000',
                'nd_adv_retrans_int': '0',
                'nd_adv_duration': '160-240',
                'nd_router_adv': '1800',
                'stateless_autoconfig': True,
                'table_id': '0xe0800000',
                'complete_protocol_adj': '1',
                'complete_glean_adj': '0',
                'incomplete_protocol_adj': '0',
                'incomplete_glean_adj': '0',
                'dropped_protocol_req': '0',
                'dropped_glean_req': '0',
            },
        },
        'GigabitEthernet0/0/0/1.120': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'default',
            'vrf_id': '0x60000000',
            'enabled': True,
            'ipv6': {
                '2001:10:23:120::2/64': {
                    'ipv6': '2001:10:23:120::2',
                    'ipv6_prefix_length': '64',
                    'ipv6_subnet': '2001:10:23:120::',
                },
                'ipv6_link_local': 'fe80::f816:3eff:fe59:8f2e',
                'ipv6_groups': ['ff02::1:ff00:2', 'ff02::1:ff59:8f2e', 'ff02::2', 'ff02::1'],
                'ipv6_mtu': '1518',
                'ipv6_mtu_available': '1500',
                'icmp_redirects': 'disabled',
                'icmp_unreachables': 'enabled',
                'nd_dad': 'enabled',
                'dad_attempts': '1',
                'nd_reachable_time': '0',
                'nd_cache_limit': '1000000000',
                'nd_adv_retrans_int': '0',
                'nd_adv_duration': '160-240',
                'nd_router_adv': '1800',
                'stateless_autoconfig': True,
                'table_id': '0xe0800000',
                'complete_protocol_adj': '0',
                'complete_glean_adj': '0',
                'incomplete_protocol_adj': '0',
                'incomplete_glean_adj': '0',
                'dropped_protocol_req': '0',
                'dropped_glean_req': '0',
            },
        },
        'GigabitEthernet0/0/0/1.390': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'VRF1',
            'vrf_id': '0x60000001',
            'enabled': True,
            'ipv6': {
                '2001:10:23:90::2/64': {
                    'ipv6': '2001:10:23:90::2',
                    'ipv6_prefix_length': '64',
                    'ipv6_subnet': '2001:10:23:90::',
                },
                'ipv6_link_local': 'fe80::f816:3eff:fe59:8f2e',
                'ipv6_groups': ['ff02::1:ff00:2', 'ff02::1:ff59:8f2e', 'ff02::2', 'ff02::1', 'ff02::a'],
                'ipv6_mtu': '1518',
                'ipv6_mtu_available': '1500',
                'icmp_redirects': 'disabled',
                'icmp_unreachables': 'enabled',
                'nd_dad': 'enabled',
                'dad_attempts': '1',
                'nd_reachable_time': '0',
                'nd_cache_limit': '1000000000',
                'nd_adv_retrans_int': '0',
                'nd_adv_duration': '160-240',
                'nd_router_adv': '1800',
                'stateless_autoconfig': True,
                'table_id': '0xe0800001',
                'complete_protocol_adj': '0',
                'complete_glean_adj': '1',
                'incomplete_protocol_adj': '0',
                'incomplete_glean_adj': '0',
                'dropped_protocol_req': '0',
                'dropped_glean_req': '0',
            },
        },
        'GigabitEthernet0/0/0/1.410': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'VRF1',
            'vrf_id': '0x60000001',
            'enabled': True,
            'ipv6': {
                '2001:10:23:110::2/64': {
                    'ipv6': '2001:10:23:110::2',
                    'ipv6_prefix_length': '64',
                    'ipv6_subnet': '2001:10:23:110::',
                },
                'ipv6_link_local': 'fe80::f816:3eff:fe59:8f2e',
                'ipv6_groups': ['ff02::1:ff00:2', 'ff02::1:ff59:8f2e', 'ff02::2', 'ff02::1', 'ff02::16', 'ff02::5', 'ff02::6', 'ff02::d'],
                'ipv6_mtu': '1518',
                'ipv6_mtu_available': '1500',
                'icmp_redirects': 'disabled',
                'icmp_unreachables': 'enabled',
                'nd_dad': 'enabled',
                'dad_attempts': '1',
                'nd_reachable_time': '0',
                'nd_cache_limit': '1000000000',
                'nd_adv_retrans_int': '0',
                'nd_adv_duration': '160-240',
                'nd_router_adv': '1800',
                'stateless_autoconfig': True,
                'table_id': '0xe0800001',
                'complete_protocol_adj': '0',
                'complete_glean_adj': '1',
                'incomplete_protocol_adj': '0',
                'incomplete_glean_adj': '0',
                'dropped_protocol_req': '0',
                'dropped_glean_req': '0',
            },
        },
        'GigabitEthernet0/0/0/1.415': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'VRF1',
            'vrf_id': '0x60000001',
            'enabled': True,
            'ipv6': {
                '2001:10:23:115::2/64': {
                    'ipv6': '2001:10:23:115::2',
                    'ipv6_prefix_length': '64',
                    'ipv6_subnet': '2001:10:23:115::',
                },
                'ipv6_link_local': 'fe80::f816:3eff:fe59:8f2e',
                'ipv6_groups': ['ff02::1:ff00:2', 'ff02::1:ff59:8f2e', 'ff02::2', 'ff02::1'],
                'ipv6_mtu': '1518',
                'ipv6_mtu_available': '1500',
                'icmp_redirects': 'disabled',
                'icmp_unreachables': 'enabled',
                'nd_dad': 'enabled',
                'dad_attempts': '1',
                'nd_reachable_time': '0',
                'nd_cache_limit': '1000000000',
                'nd_adv_retrans_int': '0',
                'nd_adv_duration': '160-240',
                'nd_router_adv': '1800',
                'stateless_autoconfig': True,
                'table_id': '0xe0800001',
                'complete_protocol_adj': '0',
                'complete_glean_adj': '0',
                'incomplete_protocol_adj': '0',
                'incomplete_glean_adj': '0',
                'dropped_protocol_req': '0',
                'dropped_glean_req': '0',
            },
        },
        'GigabitEthernet0/0/0/1.420': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'VRF1',
            'vrf_id': '0x60000001',
            'enabled': True,
            'ipv6': {
                '2001:10:23:120::2/64': {
                    'ipv6': '2001:10:23:120::2',
                    'ipv6_prefix_length': '64',
                    'ipv6_subnet': '2001:10:23:120::',
                },
                'ipv6_link_local': 'fe80::f816:3eff:fe59:8f2e',
                'ipv6_groups': ['ff02::1:ff00:2', 'ff02::1:ff59:8f2e', 'ff02::2', 'ff02::1'],
                'ipv6_mtu': '1518',
                'ipv6_mtu_available': '1500',
                'icmp_redirects': 'disabled',
                'icmp_unreachables': 'enabled',
                'nd_dad': 'enabled',
                'dad_attempts': '1',
                'nd_reachable_time': '0',
                'nd_cache_limit': '1000000000',
                'nd_adv_retrans_int': '0',
                'nd_adv_duration': '160-240',
                'nd_router_adv': '1800',
                'stateless_autoconfig': True,
                'table_id': '0xe0800001',
                'complete_protocol_adj': '0',
                'complete_glean_adj': '0',
                'incomplete_protocol_adj': '0',
                'incomplete_glean_adj': '0',
                'dropped_protocol_req': '0',
                'dropped_glean_req': '0',
            },
        },
        'GigabitEthernet0/0/0/2': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'default',
            'vrf_id': '0x60000000',
            'enabled': False,
        },
        'GigabitEthernet0/0/0/3': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'default',
            'vrf_id': '0x60000000',
            'enabled': False,
        },
        'GigabitEthernet0/0/0/4': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'default',
            'vrf_id': '0x60000000',
            'enabled': False,
        },
        'GigabitEthernet0/0/0/5': {
            'ipv6_enabled': True,
            'int_status': 'up',
            'oper_status': 'up',
            'vrf': 'default',
            'vrf_id': '0x60000000',
            'enabled': False,
        },
    }
    
    ShowRunInterface = '''\
        interface Bundle-Ether12
        !
        interface Loopback0
            ipv4 address 10.16.2.2 255.255.255.255
            ipv6 address 2001:2:2:2::2/128
        !
        interface MgmtEth0/RP0/CPU0/0
            vrf management
            ipv4 address 172.16.1.52 255.255.255.0
        !
        interface GigabitEthernet0/0/0/0
            cdp
        !
        interface GigabitEthernet0/0/0/0.90
            ipv4 address 10.12.90.2 255.255.255.0
            ipv6 nd ra-lifetime 2000
            ipv6 nd suppress-ra
            ipv6 address 2001:10:12:90::2/64
            encapsulation dot1q 90
        !
        interface GigabitEthernet0/0/0/0.110
            ipv4 address 10.12.110.2 255.255.255.0
            ipv6 address 2001:10:12:110::2/64
            encapsulation dot1q 110
        !
        '''

    ndOpsOutput = {
        'interfaces': {
            'GigabitEthernet0/0/0/1.420': {
                'interface': 'Gi0/0/0/1.420',
                'router_advertisement': {
                    'interval': '160-240',
                    'lifetime': '1800',
                },
                'neighbors': {
                    'Mcast adjacency': {
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'age': '-',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.415': {
                'interface': 'Gi0/0/0/1.415',
                'router_advertisement': {
                    'interval': '160-240',
                    'lifetime': '1800',
                },
                'neighbors': {
                    'Mcast adjacency': {
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'age': '-',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.410': {
                'interface': 'Gi0/0/0/1.410',
                'router_advertisement': {
                    'interval': '160-240',
                    'lifetime': '1800',
                },
                'neighbors': {
                    'Mcast adjacency': {
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'age': '-',
                        'origin': 'other',
                    },
                    'fe80::5c00:40ff:fe02:7': {
                        'ip': 'fe80::5c00:40ff:fe02:7',
                        'link_layer_address': '5e00.4002.0007',
                        'neighbor_state': 'REACH',
                        'age': '125',
                        'origin': 'dynamic',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.390': {
                'interface': 'Gi0/0/0/1.390',
                'router_advertisement': {
                    'interval': '160-240',
                    'lifetime': '1800',
                },
                'neighbors': {
                    'Mcast adjacency': {
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'age': '-',
                        'origin': 'other',
                    },
                    'fe80::5c00:40ff:fe02:7': {
                        'ip': 'fe80::5c00:40ff:fe02:7',
                        'link_layer_address': '5e00.4002.0007',
                        'neighbor_state': 'REACH',
                        'age': '100',
                        'origin': 'dynamic',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.120': {
                'interface': 'Gi0/0/0/1.120',
                'router_advertisement': {
                    'interval': '160-240',
                    'lifetime': '1800',
                },
                'neighbors': {
                    'Mcast adjacency': {
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'age': '-',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.115': {
                'interface': 'Gi0/0/0/1.115',
                'router_advertisement': {
                    'interval': '160-240',
                    'lifetime': '1800',
                },
                'neighbors': {
                    'Mcast adjacency': {
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'age': '-',
                        'origin': 'other',
                    },
                    'fe80::5c00:40ff:fe02:7': {
                        'ip': 'fe80::5c00:40ff:fe02:7',
                        'link_layer_address': '5e00.4002.0007',
                        'neighbor_state': 'REACH',
                        'age': '165',
                        'origin': 'dynamic',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.110': {
                'interface': 'Gi0/0/0/1.110',
                'router_advertisement': {
                    'interval': '160-240',
                    'lifetime': '1800',
                },
                'neighbors': {
                    'Mcast adjacency': {
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'age': '-',
                        'origin': 'other',
                    },
                    'fe80::5c00:40ff:fe02:7': {
                        'ip': 'fe80::5c00:40ff:fe02:7',
                        'link_layer_address': '5e00.4002.0007',
                        'neighbor_state': 'REACH',
                        'age': '17',
                        'origin': 'dynamic',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.420': {
                'interface': 'Gi0/0/0/0.420',
                'router_advertisement': {
                    'interval': '160-240',
                    'lifetime': '1800',
                },
                'neighbors': {
                    'Mcast adjacency': {
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'age': '-',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.415': {
                'interface': 'Gi0/0/0/0.415',
                'router_advertisement': {
                    'interval': '160-240',
                    'lifetime': '1800',
                },
                'neighbors': {
                    'Mcast adjacency': {
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'age': '-',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.410': {
                'interface': 'Gi0/0/0/0.410',
                'router_advertisement': {
                    'interval': '160-240',
                    'lifetime': '1800',
                },
                'neighbors': {
                    'Mcast adjacency': {
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'age': '-',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.390': {
                'interface': 'Gi0/0/0/0.390',
                'router_advertisement': {
                    'interval': '160-240',
                    'lifetime': '1800',
                },
                'neighbors': {
                    'Mcast adjacency': {
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'age': '-',
                        'origin': 'other',
                    },
                    'fe80::f816:3eff:fe26:1224': {
                        'ip': 'fe80::f816:3eff:fe26:1224',
                        'link_layer_address': 'fa16.3e26.1224',
                        'neighbor_state': 'REACH',
                        'age': '151',
                        'origin': 'dynamic',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.120': {
                'interface': 'Gi0/0/0/0.120',
                'router_advertisement': {
                    'interval': '160-240',
                    'lifetime': '1800',
                },
                'neighbors': {
                    'Mcast adjacency': {
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'age': '-',
                        'origin': 'other',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.115': {
                'interface': 'Gi0/0/0/0.115',
                'router_advertisement': {
                    'interval': '160-240',
                    'lifetime': '1800',
                },
                'neighbors': {
                    'Mcast adjacency': {
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'age': '-',
                        'origin': 'other',
                    },
                    'fe80::f816:3eff:fe26:1224': {
                        'ip': 'fe80::f816:3eff:fe26:1224',
                        'link_layer_address': 'fa16.3e26.1224',
                        'neighbor_state': 'REACH',
                        'age': '69',
                        'origin': 'dynamic',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.110': {
                'interface': 'Gi0/0/0/0.110',
                'router_advertisement': {
                    'interval': '160-240',
                    'lifetime': '1800',
                },
                'neighbors': {
                    'Mcast adjacency': {
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'age': '-',
                        'origin': 'other',
                    },
                    'fe80::f816:3eff:fe26:1224': {
                        'ip': 'fe80::f816:3eff:fe26:1224',
                        'link_layer_address': 'fa16.3e26.1224',
                        'neighbor_state': 'REACH',
                        'age': '114',
                        'origin': 'dynamic',
                    },
                },
            },
            'GigabitEthernet0/0/0/1.90': {
                'interface': 'Gi0/0/0/1.90',
                'router_advertisement': {
                    'interval': '160-240',
                    'lifetime': '1800',
                },
                'neighbors': {
                    'Mcast adjacency': {
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'age': '-',
                        'origin': 'other',
                    },
                    'fe80::5c00:40ff:fe02:7': {
                        'ip': 'fe80::5c00:40ff:fe02:7',
                        'link_layer_address': '5e00.4002.0007',
                        'neighbor_state': 'REACH',
                        'age': '151',
                        'origin': 'dynamic',
                    },
                },
            },
            'GigabitEthernet0/0/0/0.90': {
                'interface': 'Gi0/0/0/0.90',
                'router_advertisement': {
                    'suppress': True,
                },
                'neighbors': {
                    'Mcast adjacency': {
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'age': '-',
                        'origin': 'other',
                    },
                    'fe80::f816:3eff:fe26:1224': {
                        'ip': 'fe80::f816:3eff:fe26:1224',
                        'link_layer_address': 'fa16.3e26.1224',
                        'neighbor_state': 'REACH',
                        'age': '138',
                        'origin': 'dynamic',
                    },
                },
            },
        },
    }

    ShowRunInterface_custom = '''\
        interface GigabitEthernet0/0/0/0.390
            vrf VRF1
            ipv4 address 10.12.90.2 255.255.255.0
            ipv6 address 2001:10:12:90::2/64
            encapsulation dot1q 390
        !
        '''

    ndOpsOutput_custom = {
        'interfaces': {
            'GigabitEthernet0/0/0/0.390': {
                'interface': 'Gi0/0/0/0.390',
                'router_advertisement': {
                    'interval': '160-240',
                    'lifetime': '1800',
                },
                'neighbors': {
                    'Mcast adjacency': {
                        'ip': 'Mcast adjacency',
                        'link_layer_address': '0000.0000.0000',
                        'neighbor_state': 'REACH',
                        'age': '-',
                        'origin': 'other',
                    },
                    'fe80::f816:3eff:fe26:1224': {
                        'ip': 'fe80::f816:3eff:fe26:1224',
                        'link_layer_address': 'fa16.3e26.1224',
                        'neighbor_state': 'REACH',
                        'age': '151',
                        'origin': 'dynamic',
                    },
                },
            },
        },
    }
