def project = 'genielibs'


pipeline {
    agent {
        label 'linux'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
    }
    stages {
        stage('Clone repos') {
            steps {
                checkout([$class: 'GitSCM', extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'pyats']], userRemoteConfigs: [[credentialsId: 'e8a7354a-c71a-42cb-83ee-49ab5ad40085', url: 'https://wwwin-github.cisco.com/pyATS/pyats.git']]])
                checkout([$class: 'GitSCM', extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'genie']], userRemoteConfigs: [[credentialsId: 'e8a7354a-c71a-42cb-83ee-49ab5ad40085', url: 'https://wwwin-github.cisco.com/pyATS/genie.git']]])
                checkout([$class: 'GitSCM', extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'genieparser']], userRemoteConfigs: [[credentialsId: 'e8a7354a-c71a-42cb-83ee-49ab5ad40085', url: 'https://wwwin-github.cisco.com/pyATS/genieparser.git']]])
                checkout([$class: 'GitSCM', extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'unicon']], userRemoteConfigs: [[credentialsId: 'e8a7354a-c71a-42cb-83ee-49ab5ad40085', url: 'https://wwwin-github.cisco.com/pyATS/unicon.git']]])
                checkout([$class: 'GitSCM', extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'unicon.plugins']], userRemoteConfigs: [[credentialsId: 'e8a7354a-c71a-42cb-83ee-49ab5ad40085', url: 'https://wwwin-github.cisco.com/pyATS/unicon.plugins.git']]])
                checkout([$class: 'GitSCM', extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'yang']], userRemoteConfigs: [[url: 'https://github.com/CiscoTestAutomation/yang.git']]])
                checkout([$class: 'GitSCM', extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'rest']], userRemoteConfigs: [[url: 'https://github.com/CiscoTestAutomation/rest.git']]])
                checkout([$class: 'GitSCM', branches: [[name: '*/dev'], [name: '*/main']], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'genielibs.cisco']], userRemoteConfigs: [[credentialsId: 'e8a7354a-c71a-42cb-83ee-49ab5ad40085', url: 'https://wwwin-github.cisco.com/pyATS/genielibs.cisco.git']]])
                script {
                    sh """
                    ls -l
                    cd ${WORKSPACE}/pyats
                    git remote -v
                    cd ${WORKSPACE}/genie
                    git remote -v
                    cd ${WORKSPACE}/genieparser
                    git remote -v
                    cd ${WORKSPACE}/genielibs.cisco
                    git remote -v
                    cd ${WORKSPACE}/unicon
                    git remote -v
                    cd ${WORKSPACE}/unicon.plugins
                    git remote -v
                    cd ${WORKSPACE}/yang
                    git remote -v
                    cd ${WORKSPACE}/rest
                    git remote -v
                    """
                }
            }
        }


        stage('Checkout branches') {
            steps {
                script {
                    sh """
                    cd ${WORKSPACE}/pyats
                    # checkout same branch on pyats, if it exists
                    git checkout ${env.CHANGE_BRANCH == null ? env.GIT_BRANCH : env.CHANGE_BRANCH} || git checkout dev
                    git status
                    cd ${WORKSPACE}/genie
                    # checkout same branch on genie, if it exists
                    git checkout ${env.CHANGE_BRANCH == null ? env.GIT_BRANCH : env.CHANGE_BRANCH} || git checkout dev
                    git status
                    cd ${WORKSPACE}/genieparser
                    # checkout same branch on genieparser, if it exists
                    git checkout ${env.CHANGE_BRANCH == null ? env.GIT_BRANCH : env.CHANGE_BRANCH} || git checkout dev
                    git status
                    cd ${WORKSPACE}/genielibs.cisco
                    # checkout same branch on genielibs.cisco, if it exists
                    git checkout ${env.CHANGE_BRANCH == null ? env.GIT_BRANCH : env.CHANGE_BRANCH} || git checkout dev
                    git status
                    cd ${WORKSPACE}/unicon
                    # checkout same branch on unicon, if it exists
                    git checkout ${env.CHANGE_BRANCH == null ? env.GIT_BRANCH : env.CHANGE_BRANCH} || git checkout dev
                    git status
                    cd ${WORKSPACE}/unicon.plugins
                    # checkout same branch on unicon.plugins, if it exists
                    git checkout ${env.CHANGE_BRANCH == null ? env.GIT_BRANCH : env.CHANGE_BRANCH} || git checkout dev
                    git status
                    cd ${WORKSPACE}/yang
                    # checkout same branch on yang, if it exists
                    git checkout ${env.CHANGE_BRANCH == null ? env.GIT_BRANCH : env.CHANGE_BRANCH} || git checkout master
                    git status
                    cd ${WORKSPACE}/rest
                    # checkout same branch on rest, if it exists
                    git checkout ${env.CHANGE_BRANCH == null ? env.GIT_BRANCH : env.CHANGE_BRANCH} || git checkout master
                    git status
                    """
                }
            }
        }


        stage("Build pyATS and make develop") {
            steps {
                sh """
                    env
                    pip list
                    pip freeze
                    export PIP_DOWNLOAD_CACHE=/scratch/pip_download_cache
                    export LC_ALL=C.UTF-8
                    rm -rf /scratch/genielibs-env
                    cd /scratch
                    /scratch/pyadm/.pyenv/versions/3.8.8/bin/python -m venv genielibs-env
                    . /scratch/genielibs-env/bin/activate
                    pip install --upgrade pip setuptools
                    pip3 install --no-cache-dir wheel pytest pytest-xdist
                    pip3 install --no-cache-dir -i http://pyats-pypi.cisco.com/simple --trusted-host pyats-pypi.cisco.com cisco-distutils ats[full]
                    cd $WORKSPACE/yang/connector
                    make develop
                    cd $WORKSPACE/rest
                    make develop
                    cd $WORKSPACE/unicon
                    make develop
                    cd $WORKSPACE/unicon.plugins
                    make develop
                    cd $WORKSPACE/genie
                    make develop
                    make json
                    cd $WORKSPACE/genieparser
                    make develop
                    cd $WORKSPACE/genielibs.cisco
                    make develop
                    cd $WORKSPACE/pyats
                    make develop
                    cd $WORKSPACE
                    make develop

                    make json
                    make -C $WORKSPACE/genieparser json
                    make -C $WORKSPACE/genielibs.cisco json
                    make -C $WORKSPACE/genie json

                    cd $WORKSPACE
                    git diff --exit-code pkgs/sdk-pkg/api_generator/output/github_apis.json || (echo "API JSON may be corrupted. Ensure your branch is up to date, run 'make json', and re-push to branch" && false)
                    git diff --exit-code pkgs/ops-pkg/ops_generator/output/github_ops.json || (echo "Ops JSON may be corrupted. Ensure your branch is up to date, run 'make json', and re-push to branch" && false)
                    git diff --exit-code pkgs/clean-pkg/sdk_generator/output/github_clean.json || (echo "Clean JSON may be corrupted. Ensure your branch is up to date, run 'make json', and re-push to branch" && false)

                    env
                    pip list
                    pip freeze
                """
            }
        }

        stage("Run compileAll") {
            steps {
                sh """
                . /scratch/genielibs-env/bin/activate
                compileAll --path=src
                """
            }
        }
        
        stage("Test changelogs") {
            steps {
                sh"""
                . /scratch/genielibs-env/bin/activate
                make changelogs
                """
            }
        }


        stage("Run runAll") {
            steps {
                sh """
                . /scratch/genielibs-env/bin/activate
                cd tests
                runAll --no-refresh
                """

            }
        }

        stage("Run Tests for Coverage") {
            steps {
                sh """
                . /scratch/genielibs-env/bin/activate
                coverage erase
                coverage run --include 'pkgs/*' --omit='*/tests/*' -m unittest discover -s tests/api -v
                mv .coverage .coverage.api
                coverage run --include 'pkgs/*' --omit='*/tests/*' -m unittest discover -s tests/clean -v
                mv .coverage .coverage.clean
                coverage run --include 'pkgs/*' --omit='*/tests/*' -m unittest discover -s tests/filetransferutils -v
                mv .coverage .coverage.filetransferutils
                coverage run --include 'pkgs/*' --omit='*/tests/*' -m unittest discover -s tests/iosxe -v
                mv .coverage .coverage.iosxe
                coverage run --include 'pkgs/*' --omit='*/tests/*' -m unittest discover -s tests/robot -v
                mv .coverage .coverage.robot
                coverage run --include 'pkgs/*' --omit='*/tests/*' -m unittest discover -s tests/blitz -v
                mv .coverage .coverage.blitz
                coverage run --include 'pkgs/*' --omit='*/tests/*' -m unittest discover -s tests/conf -v
                mv .coverage .coverage.conf
                coverage run --include 'pkgs/*' --omit='*/tests/*' -m unittest discover -s tests/health -v
                mv .coverage .coverage.health
                coverage combine
                coverage report
                coverage html
                """
                publishHTML (target: [
                    allowMissing: true,
                    alwaysLinkToLastBuild: false,
                    keepAll: true,
                    reportDir: 'htmlcov',
                    reportFiles: "index.html",
                    reportName: 'Coverage report'
                ])
            }
        }

        stage("Run runAll (without genie.libs.cisco)") {
            steps {
                sh """
                . /scratch/genielibs-env/bin/activate
                cd $WORKSPACE/genie
                pip uninstall -y genie
                make clean
                make devnet
                pip install __build__/dist/genie*
                pip uninstall -y genie.libs.cisco
                cd $WORKSPACE
                cd tests
                runAll --no-refresh
                """
            }
        }

    }
    post {
        cleanup {
            cleanWs()
        }
    }
}
